### ISSUE TITLE
AniList "Hide from status lists" feature does not hide things in Aluminium

### ISSUE THREAD

**Issue by toasterovenly** [Emplexx/Aluminium#17]
This is an AniList feature where you can add something to your list, but then when you view your list, it won't actually appear there. If you got to the media page itself, then it will show it with whatever status you have applied. In Aluminium for AniList, things that are hidden still appear when I view my lists.

I suspect, but have not verified that the "private" checkbox right next to "Hide from status lists" on AniList also might not work. Here's a description of that feature from [this thread on MAL](https://myanimelist.net/forum/?topicid=1844600).

>On Anilist you can click a little check box when you go to add an entry that says "Private" and while that's checked it will never show episode count updates, completion, etc. on your activity feed, nor will it show up under your anime list if someone goes to search for it.

![Screenshot_2024-05-08-15-00-23_firefox](https://github.com/Emplexx/Aluminium/assets/16892650/db67cd29-7d45-44cf-ba8c-66b2c533ea7b)

**Comment by Emplexx** [comment]
Both "Hide from status lists" and "Private" toggles are consistent with the website, you could test this by checking either option, saving the entry, then opening the entry on the website - or the other way around - you'll see the same options selected 

The former doesn't hide entries from your list, it only hides them from *status* lists - that's Planning/Watching/Completed/Rewatching/Paused/Dropped (and manga equivalents) - and it's meant to be used together with custom lists, it's basically a means to make a certain entry *only* show up on custom lists. If you "Hide" something that's also added to a custom list it will still appear in your list, only in the section of that custom list.

I'm not sure if I understood you correctly to be honest, but please do clarify if I didn't. (But assuming I did, I guess this might be indication that the "hide from status lists" option is not intuitively named and could use a little explanation in the editor for what it actually does.)

**Comment by toasterovenly** [comment]
I do not see that. On the AniList website when viewing my anime list I see 16 items as "watching" and 3 shows as "rewatching". In Aluminium, I see 20 shows in the "watching" list which combines with "rewatching". 16 watching + 3 rewatching + 1 extra = 20. The extra item is one that is marked as both private and hide from status lists in AniList (I had to search it up to see that, because it isn't in my list). In Aluminium if I click on the extra item, it shows the status as "+ Add to list". If I click on that it populates the data in the add to list menu with the correct data: status=watching, episodesWatched=8, etc. and then the media page shows it as "watching" but it is still shown in my list while it isn't in my list on the website.

Please note that I am not providing screenshots because I have it marked private and hidden and don't want to show it off.

**Comment by toasterovenly** [comment]
Screenshots with numbers.
![image](https://github.com/Emplexx/Aluminium/assets/16892650/81fed641-bcba-4a5f-8d51-e3309b12bc12)
![Screenshot_20240508-171754](https://github.com/Emplexx/Aluminium/assets/16892650/924a61b4-7b8a-4461-934b-d677dc687bf6)

**Comment by toasterovenly** [comment]
Ah shoot. Just realized this bug is only on the homepage.

**Comment by Emplexx** [comment]
Oh now I get it, you were talking about the home page and not the media list page

Well, I see nothing wrong here, because the home page replicates the websites "in progress" section and is meant for updating current stuff as quickly as possible, so it just shows everything (actually as much as possible) that's in progress on your list. And this behaviour is also consistent with the website, I just tested it - if I set something as watching or reading, even if I hide it from status lists, on the website it still shows up on the in progress section on the home page

I'm guessing the use case here is that you don't want that particular entry to be seen on your list even by you ("private" already hides it from everyone else) and so you don't want to see it on the home page either, I guess one way I could fix it is manually filter out these "fully hidden" entries from the home page. 

Regarding this weird behaviour:
> if I click on the extra item, it shows the status as "+ Add to list". If I click on that it populates the data in the add to list menu with the correct data: status=watching, episodesWatched=8, etc. and then the media page shows it as "watching"

This is a problem that I've been aware of and know the cause of, basically the app fetches your entire list upfront on launch and keeps it up to date as you edit your list. This is also where it pulls all of the data from later (for example for the entry previews that can be opened on almost any screen or the button with the status on the media page) Since hidden entries with no custom lists don't show up on the list, the app doesn't get them in that initial request either, and doesn't know that they exist. When you click on add to list it opens the entry editor which always fetches the latest entry before letting you edit. That puts it in the cache and so the app now knows about it.

**Comment by toasterovenly** [comment]
Ah. I see. I have never even looked at the in progress section before. It's as you said. I can see the hidden show there on the AniList website. I guess I'll see if there's a way to file a bug report with AniList themselves because it feels wrong to show a hidden anime there.

**Comment by Emplexx** [comment]
I could still add an option for the desired behaviour in Aluminium, so feel free to reopen this
