### ISSUE TITLE
Treat unix epoch date on media list entries as a missing date

### ISSUE THREAD

**Issue by Fmoment1** [Emplexx/Aluminium#32]
For some reason, when I imported my lists from MAL to AL, all my anime/manga dates were set to Jan 1, 1970 and it's so weird seeing that all the time in-app. 

![IMG_15161080](https://github.com/user-attachments/assets/da45cb9c-081b-43f3-a3e0-3d4367f72c40)

I'd just really like an option to hide these dates, or replace these dates with the starting date of the anime (as in, which year the anime started, not when I started the anime).

Would really appreciate it if this was considered!

PS: I also want to clarify that I never used the start date/end date feature anyway and I don't want to see them even without the date anomaly.

**Comment by Emplexx** [comment]
The highlighted information (in this case the date) depends on the sorting mode. This is just a QoL feature - for example let's say you're sorting by average score. On the AniList website it just lets you know which anime is rated higher, but you don't know the actual rating itself unless you open the anime page to check. Here if you were to sort by score it would show the percentages right there. In this case I'm assuming you're sorting the list by date added, so it tries to show you that date. If you were to sort the list by release date, it would show the date when anime started, etc 

But this isn't really intentional, ideally it should treat Jan 1 1970 (the Unix epoch) as a missing date, so I'll fix this behaviour later

**Comment by Fmoment1** [comment]
>In this case I'm assuming you're sorting the list by date added, so it tries to show you that date. If you were to sort the list by release date, it would show the date when anime started, etc

YES! I should've tinkered around a little before posting, thank you. I suppose I should keep this issue open because of the Unix epoch thing?

**Comment by Emplexx** [comment]
> I suppose I should keep this issue open because of the Unix epoch thing?

Yep

**Comment by Emplexx** [comment]
This should be fixed in 0.3.17, could you please confirm? 
Also, if you want an option to specifically hide these dates (or sorting hints in general) entirely, please feel free to open another issue

**Comment by Fmoment1** [comment]
Fixed in 0.3.17!
